apiVersion: v1
kind: Service
metadata:
  name: temp-monitor-microservice
spec:
  selector:
    app: temp-monitor-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30180
  type: NodePort